name: Deploy

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            domain: playground.bijanprogrammer.com
            base-href: /intersection-observer/
        secrets: inherit
